name: Build
on: [push]

jobs:
  buildlib:
    runs-on: ubuntu-latest
    name: Check python
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Prepare pip
        run: python -m pip install --upgrade pip
      - name: Install dev dependencies for lib
        run: pip install -e .[dev]
      - name: Install dev dependencies for app
        run: pip install -r afscgapviz/requirements.txt
      - name: Install afscgap
        run: pip install .
      - name: Unit tests main
        run: nose2
      - name: Unit test app
        run: nose2 --start-dir=afscgapviz
      - name: Check types
        run: mypy **/*.py
      - name: Check errors
        run: pyflakes **/*.py
      - name: Check style
        run: pycodestyle **/*.py
  buildviz:
    runs-on: ubuntu-latest
    name: Check js
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: bash install_browser.sh
      - name: Compile with Grunt
        uses: elstudio/actions-js-build/build@v4
