# Thanks https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml
# Under the unlicense license (https://github.com/mitmproxy/pdoc/blob/main/LICENSE).

name: Docs and app

on:
  workflow_run:
    workflows: 
      - build
    branches:
      - main
    types: 
      - completed

permissions:
  contents: read

jobs:
  
  build:
    environment: deployweb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: pip install -e .[dev]
      - name: Build API docs
        run: pdoc --docformat google ./afscgap -o website/devdocs/
      - name: Update apt cache
        run: sudo apt-get update
      - name: Build paper
        run: cd inst; bash preview_paper.sh
      - name: Upload website
        id: uploadWebsite
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './website'
          remotePath: './pyafscgap.org'
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: bash reload_afscgap.sh
