# Thanks https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml
# Under the unlicense license (https://github.com/mitmproxy/pdoc/blob/main/LICENSE).

name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -e .[dev]
      - run: pdoc --docformat google ./afscgap -o website/devdocs/

  deploy:
    environment: deployweb
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload static
        id: uploadStatic
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './website'
          remotePath: './pyafscgap.org/public'
